import { jsPDF } from 'jspdf';
import { WEEKDAYS, type ReportData } from './progress-report-data';

// Premium black + gold, same palette as the app
const BG: [number, number, number] = [9, 9, 11];
const CARD: [number, number, number] = [20, 20, 24];
const LINE: [number, number, number] = [38, 38, 43];
const GOLD: [number, number, number] = [210, 162, 38];
const SOFT: [number, number, number] = [233, 196, 104];
const TEXT: [number, number, number] = [244, 244, 245];
const MUTE: [number, number, number] = [161, 161, 170];

const PAGE_W = 210;
const PAGE_H = 297;
const M = 16; // page margin
const CONTENT_W = PAGE_W - M * 2;

/** The built-in PDF fonts only cover Latin-1. Drop anything else so names never turn into garbage. */
const safe = (value: string) => value.replace(/[^ -ÿ]/g, '').trim();

export function buildProgressReportPdf(data: ReportData): jsPDF {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    let y = M;
    let page = 1;

    const paintPage = () => {
        doc.setFillColor(...BG);
        doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
    };
    const footer = () => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(...MUTE);
        doc.text('Planner data, not self-reported. Generated by Legacy Life Builder.', M, PAGE_H - 8);
        doc.text(`Page ${page}`, PAGE_W - M, PAGE_H - 8, { align: 'right' });
    };
    const newPage = () => {
        footer();
        doc.addPage();
        page += 1;
        paintPage();
        y = M;
    };
    const need = (h: number) => {
        if (y + h > PAGE_H - 16) newPage();
    };

    const heading = (title: string) => {
        need(18);
        y += 4;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(...GOLD);
        doc.text(title.toUpperCase().split('').join(' '), M, y);
        y += 2;
        doc.setDrawColor(...LINE);
        doc.line(M, y, PAGE_W - M, y);
        y += 6;
    };

    const bar = (x: number, yy: number, w: number, pct: number) => {
        doc.setFillColor(...LINE);
        doc.roundedRect(x, yy, w, 2, 1, 1, 'F');
        if (pct > 0) {
            doc.setFillColor(...GOLD);
            doc.roundedRect(x, yy, Math.max(2, (w * Math.min(100, pct)) / 100), 2, 1, 1, 'F');
        }
    };

    // A labelled bar row: name on the left, bar in the middle, value on the right
    const barRow = (label: string, pct: number, right: string, sub?: string) => {
        need(sub ? 12 : 8);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...TEXT);
        doc.text(safe(label).slice(0, 38), M, y);
        bar(M + 70, y - 2, 70, pct);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...SOFT);
        doc.text(right, PAGE_W - M, y, { align: 'right' });
        y += 4.5;
        if (sub) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7.5);
            doc.setTextColor(...MUTE);
            doc.text(safe(sub).slice(0, 90), M, y);
            y += 4;
        }
        y += 1.5;
    };

    const bullets = (items: string[]) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        items.forEach((item) => {
            const lines = doc.splitTextToSize(safe(item), CONTENT_W - 6) as string[];
            need(lines.length * 4.6 + 2);
            doc.setTextColor(...GOLD);
            doc.text('-', M, y);
            doc.setTextColor(...TEXT);
            doc.text(lines, M + 5, y);
            y += lines.length * 4.6 + 1.5;
        });
    };

    // ---------- Cover block ----------
    paintPage();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...GOLD);
    doc.text('L E G A C Y   L I F E   B U I L D E R   -   F U L L   P R O G R E S S   R E P O R T', M, y + 2);
    y += 14;
    doc.setFontSize(26);
    doc.setTextColor(...TEXT);
    doc.text(safe(data.name) || 'Legacy Builder', M, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...MUTE);
    const sub = `${data.firstDay ? `Every day from ${data.firstDay} to ${data.generatedOn}.` : `Generated ${data.generatedOn}.`}${data.stageTitle ? ` Stage reached: ${data.stageTitle}.` : ''}`;
    doc.text(safe(sub), M, y);
    y += 10;

    // Headline tiles
    const tiles: [string, string][] = [
        [String(data.headline.daysExecuted), 'DAYS EXECUTED'],
        [String(data.headline.currentStreak), 'CURRENT STREAK'],
        [String(data.headline.longestStreak), 'LONGEST STREAK'],
        [`${data.headline.consistency}%`, 'CONSISTENCY'],
        [String(data.headline.lifeScore), 'LIFE SCORE'],
    ];
    const tileW = (CONTENT_W - 4 * 3) / 5;
    tiles.forEach(([value, label], i) => {
        const x = M + i * (tileW + 3);
        doc.setFillColor(...CARD);
        doc.setDrawColor(...LINE);
        doc.roundedRect(x, y, tileW, 22, 2, 2, 'FD');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(17);
        doc.setTextColor(...SOFT);
        doc.text(value, x + tileW / 2, y + 11, { align: 'center' });
        doc.setFontSize(6);
        doc.setTextColor(...MUTE);
        doc.text(label, x + tileW / 2, y + 17, { align: 'center' });
    });
    y += 26;

    // ---------- What your days say ----------
    if (data.insights.length) {
        heading('What your days say');
        bullets(data.insights);
    }

    // ---------- The numbers ----------
    heading('The numbers');
    const colW = CONTENT_W / 2;
    data.totals.forEach((row, i) => {
        if (i % 2 === 0) need(7);
        const x = M + (i % 2) * colW;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(...MUTE);
        doc.text(safe(row.label), x, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...TEXT);
        doc.text(safe(row.value), x + colW - 6, y, { align: 'right' });
        if (i % 2 === 1 || i === data.totals.length - 1) y += 6;
    });

    // ---------- Life score ----------
    heading('Life score breakdown');
    data.score.forEach((s) => barRow(s.label, (s.value / s.of) * 100, `${s.value} / ${s.of}`));

    // ---------- Strongest days ----------
    heading('Your week, by weekday');
    data.weekdays.forEach((w) => barRow(w.label, w.pct, `${w.tasks} tasks`));

    // ---------- Months ----------
    if (data.months.length) {
        heading('Month by month');
        data.months.forEach((m) =>
            barRow(m.label, (m.daysExecuted / Math.max(1, m.daysInMonth)) * 100, `${m.daysExecuted}/${m.daysInMonth} days`, `${m.tasks} tasks completed`),
        );
    }

    // ---------- Goals / habits ----------
    if (data.goals.length) {
        heading('Goals');
        data.goals.forEach((g) => barRow(g.name, g.progress, `${g.progress}%`, g.detail));
    }
    if (data.habits.length) {
        heading('Habits');
        data.habits.forEach((h) => barRow(h.name, h.consistency, `${h.consistency}%`, h.detail));
    }

    // ---------- Life balance ----------
    if (data.buckets.length) {
        heading('Life balance this week');
        const maxHours = Math.max(1, ...data.buckets.map((b) => b.hours));
        data.buckets.forEach((b) => barRow(b.label, (b.hours / maxHours) * 100, `${b.hours} h`, `Balance score ${b.score} / 10`));
    }

    // ---------- Weekly execution ----------
    if (data.weeklyExecution.length) {
        heading('Weekly execution, last 12 weeks');
        data.weeklyExecution.forEach((w) => barRow(w.label, w.efficiency, `${w.efficiency}%`, `${w.completed} tasks done, ${w.planned} planned`));
    }

    // ---------- Milestones ----------
    heading('Milestones');
    data.stages.forEach((s) => barRow(s.title, s.reached ? 100 : 0, s.reached ? 'Reached' : `${s.days} days`));
    if (data.nextStage) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...MUTE);
        need(8);
        doc.text(safe(`Next: ${data.nextStage.title}, ${data.nextStage.daysToGo} ${data.nextStage.daysToGo === 1 ? 'day' : 'days'} to go.`), M, y);
        y += 6;
    }

    // ---------- Day by day ----------
    heading('Day by day');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTE);
    doc.text('Each cell is the number of planned tasks completed that day. A day counts as executed when at least one is done.', M, y);
    y += 6;

    const labelW = 40;
    const cellW = (CONTENT_W - labelW - 14) / 7;
    const drawHeader = () => {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(...MUTE);
        doc.text('WEEK', M, y);
        WEEKDAYS.forEach((d, i) => doc.text(d.toUpperCase(), M + labelW + i * cellW + cellW / 2, y, { align: 'center' }));
        doc.text('DONE', PAGE_W - M, y, { align: 'right' });
        y += 3;
    };
    drawHeader();
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    [...data.weeks].reverse().forEach((w) => {
        if (y + 7 > PAGE_H - 16) {
            newPage();
            drawHeader();
        }
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...TEXT);
        doc.text(safe(w.label), M, y + 4.2);
        w.days.forEach((d, i) => {
            const x = M + labelW + i * cellW;
            const future = d.date > today;
            if (!future) {
                doc.setFillColor(...(d.done > 0 ? ([86, 66, 18] as [number, number, number]) : CARD));
                doc.roundedRect(x + 0.6, y, cellW - 1.2, 5.6, 1, 1, 'F');
                doc.setTextColor(...(d.done > 0 ? SOFT : MUTE));
                doc.setFont('helvetica', d.done > 0 ? 'bold' : 'normal');
                doc.text(d.done > 0 ? String(d.done) : '-', x + cellW / 2, y + 4, { align: 'center' });
            }
        });
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...SOFT);
        doc.text(String(w.total), PAGE_W - M, y + 4.2, { align: 'right' });
        y += 7;
    });

    // Ending note
    need(14);
    y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...SOFT);
    doc.text('Keep showing up. The next day is already on your planner.', PAGE_W / 2, y, { align: 'center' });

    footer();
    return doc;
}

export function downloadProgressReportPdf(data: ReportData) {
    const doc = buildProgressReportPdf(data);
    const slug = safe(data.name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'report';
    doc.save(`legacy-progress-report-${slug}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
