// Moved to @llb/core (platform-agnostic, generated by `supabase gen types`).
// Re-exported here so existing `@/types/database.types` imports keep
// working unchanged.
export { type Json, type Database } from '@llb/core';
