import React from 'react';
import { View } from 'react-native';
import { Image } from 'expo-image';
import { Calendar, Check, RotateCw, Sparkles, X } from 'lucide-react-native';
import type { AIGeneratedPlanSlot } from '@llb/core';
import { Button } from '@/components/ui/button';
import { Text } from '@/components/ui/typography';

interface AIGenerationStepProps {
  onGenerate: () => void;
  generating: boolean;
  previewPlan?: AIGeneratedPlanSlot[] | null;
  onConfirm?: () => void;
  onCancelPreview?: () => void;
}

export const AIGenerationStep: React.FC<AIGenerationStepProps> = ({
  onGenerate,
  generating,
  previewPlan,
  onConfirm,
  onCancelPreview,
}) => {
  if (!previewPlan) return null;

  return (
    <View className="gap-4">
      <View className="flex-row items-center justify-between pb-3 border-b border-border">
        <View className="flex-row items-center gap-2">
          <Image
            source={require('../../../../assets/images/ai-animation-white.gif')}
            style={{ width: 28, height: 28 }}
            contentFit="contain"
          />
          <View>
            <Text className="text-base font-bold text-foreground">Your Roadmap</Text>
            <Text variant="tiny" className="uppercase tracking-widest">
              {previewPlan.length} milestones crafted
            </Text>
          </View>
        </View>
      </View>

      <View className="gap-3">
        {previewPlan.map((slot, index) => (
          <View key={index} className="flex-row rounded-xl border border-border bg-card overflow-hidden">
            <View className="w-1 bg-primary/40" />
            <View className="flex-1 p-4 gap-2">
              <View className="flex-row items-center gap-3">
                <View className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 items-center justify-center">
                  <Text className="font-black text-sm text-primary">{index + 1}</Text>
                </View>
                <Text className="font-bold text-sm text-foreground flex-1">{slot.dayTask}</Text>
              </View>
              <Text variant="small">{slot.description}</Text>
              <View className="flex-row items-center gap-1.5 self-start bg-muted border border-border px-2 py-0.5 rounded">
                <Calendar size={9} color="#a1a1aa" />
                <Text variant="tiny" className="font-bold">
                  {slot.date}
                </Text>
              </View>
            </View>
          </View>
        ))}
      </View>

      <View className="flex-row items-center justify-center gap-2 pt-1">
        <Sparkles size={10} color="#a1a1aa" />
        <Text variant="tiny">Generated by Legacy Planner based on your profile</Text>
      </View>

      <View className="flex-row gap-2 pt-2">
        <Button variant="ghost" onPress={onCancelPreview} disabled={generating} className="flex-1">
          <View className="flex-row items-center gap-1.5">
            <X size={14} color="#a1a1aa" />
            <Text variant="small">Cancel</Text>
          </View>
        </Button>
        <Button variant="ghost" onPress={onGenerate} disabled={generating} className="flex-1">
          <View className="flex-row items-center gap-1.5">
            <RotateCw size={14} color="#a1a1aa" />
            <Text variant="small">Remake</Text>
          </View>
        </Button>
        <Button onPress={onConfirm} disabled={generating} className="flex-1">
          <View className="flex-row items-center gap-1.5">
            <Check size={14} color="#000000" />
            <Text className="text-primary-foreground font-semibold text-xs">Save Plan</Text>
          </View>
        </Button>
      </View>
    </View>
  );
};
